apiVersion: v1
appVersion: master
description: High Performance, Kubernetes Native Object Storage
home: https://min.io
icon: file://../logo.png
keywords:
- storage
- object-storage
- S3
maintainers:
- email: dev@minio.io
  name: MinIO, Inc
name: minio
sources:
- https://github.com/minio/minio
version: 7.0.1
