apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2020-08-09T13:20:41Z"
  creationTimestamp: "2020-05-08T09:38:55Z"
  labels:
    chart: elasticsearch
    service_name: cpaas-elasticsearch
  name: cpaas-elasticsearch
  namespace: cpaas-system
  resourceVersion: "121540018"
  selfLink: /api/v1/namespaces/cpaas-system/endpoints/cpaas-elasticsearch
  uid: 4cf7983b-a683-4aff-ac96-c66ad9eb7b8f
subsets:
- addresses:
  - ip: 25.2.20.46
    nodeName: 25.2.20.46
    targetRef:
      kind: Pod
      name: cpaas-elasticsearch-594bfb97f4-nw5b2
      namespace: cpaas-system
      resourceVersion: "121539711"
      uid: a81300e1-f4aa-41d0-876b-19fc2a8d7f93
  - ip: 25.2.20.47
    nodeName: 25.2.20.47
    targetRef:
      kind: Pod
      name: cpaas-elasticsearch-594bfb97f4-hsbpx
      namespace: cpaas-system
      resourceVersion: "121539777"
      uid: 77dd90e0-8dda-4e30-8f23-44c1f08b77da
  - ip: 25.2.20.48
    nodeName: 25.2.20.48
    targetRef:
      kind: Pod
      name: cpaas-elasticsearch-594bfb97f4-86f6c
      namespace: cpaas-system
      resourceVersion: "121540016"
      uid: 0d6db097-dc9a-4336-aa3d-6e56ce8856d3
  ports:
  - name: cpaas-elasticsearch
    port: 9200
    protocol: TCP
