apiVersion: v1
appVersion: "7"
description: Datadog Agent
home: https://www.datadoghq.com
icon: file://../logo.png
keywords:
- monitoring
- alerting
- metric
maintainers:
- email: support@datadoghq.com
  name: Datadog
name: datadog
sources:
- https://app.datadoghq.com/account/settings#agent/kubernetes
- https://github.com/DataDog/datadog-agent
version: 2.4.15
