global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.yeah.net:465'             #邮箱smtp服务器代理，启用SSL发信, 端口一般是465
  smtp_from: 'xshrim@yeah.net'              #发送邮箱名称
  smtp_auth_username: 'xshrim@yeah.net'              #邮箱名称
  smtp_auth_password: 'WIOSQZQOPBNCHIGT'                #邮箱密码或授权码
  smtp_require_tls: false

route:
  receiver: 'default'
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  group_by: ['alertname']

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'instance']
  
receivers:
- name: 'default'
  email_configs:
  - to: 'receiver@163.com'
    send_resolved: true
  webhook_configs:
  - url: 'http://dingtalk:8060/dingtalk/webhook/send'
    send_resolved: true
