apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: registries.management.cattle.io
spec:
  group: management.cattle.io
  version: v1alpha1
  names:
    kind: Registry
    listKind: RegistryList
    plural: registries
    singular: registry
  scope: Cluster
  subresources:
    status: {}
