apiVersion: apps/v1
kind: Deployment
metadata:
  name: logbench
  labels:
    app: logbench
spec:
  replicas: 100
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 10
  #    maxUnavailable: 5
  #  type: RollingUpdate
  selector:
    matchLabels:
      app: logbench
  template:
    metadata:
      labels:
        app: logbench
    spec:
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: ebcpaas.com/project
          operator: Equal
          value: ebmpaas
      containers:
        - name: logbench
          image: gregistry.ebcpaas.mp.io:80/library/logbench
          imagePullPolicy: Always
          env:
            - name: LOGBENCH_PREFIX
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOGBENCH_COUNT
              value: "60000"
            - name: LOGBENCH_DURATION
              value: 10m
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
