apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{name}}
  labels:
    app: logbench
spec:
  replicas: 1
  #strategy:
  #  rollingUpdate:
  #    maxSurge: 10
  #    maxUnavailable: 5
  #  type: RollingUpdate
  selector:
    matchLabels:
      app: logbench
  template:
    metadata:
      labels:
        app: logbench
    spec:
      restartPolicy: Always
      tolerations:
        - effect: NoSchedule
          key: ebcpaas.com/project
          operator: Equal
          value: ebmpaas
      containers:
        - name: {{name}}
          image: gregistry.ebcpaas.mp.io:80/library/logbench
          imagePullPolicy: IfNotPresent
          env:
            - name: LOGBENCH_PREFIX
              value: "{{label}}"
            - name: LOGBENCH_COUNT
              value: "{{count}}"
            - name: LOGBENCH_SIZE
              value: "{{size}}"
            - name: LOGBENCH_DURATION
              value: {{duration}}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
