apiVersion: v1
kind: Service
metadata:
  labels:
    app: baas
    cluster: mysqlmm
  name: mysqlmm
  namespace: baas
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: baas
    cluster: mysqlmm
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baas
    role: mysql-1
  name: mysql-1
  namespace: baas
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: baas
    role: mysql-1
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: baas
    role: mysql-2
  name: mysql-2
  namespace: baas
spec:
  ports:
    - name: "3306"
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: baas
    role: mysql-2
  sessionAffinity: None
  type: ClusterIP
