apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2020-05-08T09:37:42Z"
  creationTimestamp: "2020-05-08T09:37:42Z"
  labels:
    app: exporter-kube-state
    chart: exporter-kube-state-0.2.5
    component: kube-state
    heritage: Helm
    release: kube-prometheus
  name: kube-prometheus-exporter-kube-state
  namespace: cpaas-system
  resourceVersion: "121571610"
  selfLink: /api/v1/namespaces/cpaas-system/endpoints/kube-prometheus-exporter-kube-state
  uid: d6c31d63-4664-46ed-a3d4-a32b6b27f221
subsets:
- addresses:
  - ip: 10.199.11.120
    nodeName: 25.2.20.55
    targetRef:
      kind: Pod
      name: kube-prometheus-exporter-kube-state-795bd9d68-zfsnd
      namespace: cpaas-system
      resourceVersion: "121540668"
      uid: 818ae05c-b557-4833-b245-d3e392c4132d
  ports:
  - name: self-metrics
    port: 8081
    protocol: TCP
  - name: kube-state-metrics
    port: 8080
    protocol: TCP
