apiVersion: v1
appVersion: "1.0"
description: Open source, scalable graph database.
home: http://janusgraph.org
icon: file://../logo.png
maintainers:
- email: samiz@google.com
  name: samizuh
name: janusgraph
sources:
- https://github.com/JanusGraph/janusgraph
version: 0.2.3
