{{- if .Values.shards }}
{{- $replicas := .Values.shards | int }}
{{- range $i, $e := until $replicas }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ printf "%s-shard%d-data" (include "mongodb-sharded.fullname" $ ) $i }}
  labels: {{- include "mongodb-sharded.labels" $ | nindent 4 }}
    app.kubernetes.io/component: shardsvr
spec:
  selector:
    matchLabels: {{- include "mongodb-sharded.matchLabels" $ | nindent 6 }}
      app.kubernetes.io/component: shardsvr
  podManagementPolicy: {{ $.Values.shardsvr.dataNode.podManagementPolicy }}
  updateStrategy: {{- toYaml $.Values.shardsvr.dataNode.updateStrategy | nindent 4 }}
  serviceName: {{ include "mongodb-sharded.fullname" $ }}-headless
  replicas: {{ $.Values.shardsvr.dataNode.replicas }}
  template:
    metadata:
      labels: {{- include "mongodb-sharded.labels" $ | nindent 8 }}
        app.kubernetes.io/component: shardsvr
        {{- if $.Values.shardsvr.dataNode.podLabels }}
          {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.podLabels "context" $ ) | nindent 8 }}
        {{- end }}
        shard: {{ $i | quote }}
      {{- if or $.Values.common.podAnnotations $.Values.shardsvr.dataNode.podAnnotations $.Values.metrics.enabled }}
      annotations:
        {{- if $.Values.common.podAnnotations }}
           {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.common.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if $.Values.shardsvr.dataNode.podAnnotations }}
          {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if $.Values.metrics.enabled }}
           {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.metrics.podAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- if $.Values.common.schedulerName }}
      schedulerName: {{ $.Values.common.schedulerName | quote }}
      {{- end }}
      nodeSelector: {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.nodeSelector "context" $ ) | nindent 8 }}
      affinity: {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.affinity "context" (set $ "dataNodeLoopId" $i) ) | nindent 8 }}
      tolerations: {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.tolerations "context" $ ) | nindent 8 }}
      serviceAccountName: {{ include "mongodb-sharded.serviceAccountName" (dict "value" $.Values.shardsvr.dataNode.serviceAccount "context" $) }}
      {{- if $.Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ $.Values.securityContext.fsGroup }}
      {{- end }}
      {{- include "mongodb-sharded.imagePullSecrets" $ | nindent 6 }}
      initContainers:
        {{- if and $.Values.volumePermissions.enabled $.Values.shardsvr.persistence.enabled }}
        - name: volume-permissions
          image: {{ include "mongodb-sharded.volumePermissions.image" $ }}
          imagePullPolicy: {{ $.Values.volumePermissions.image.pullPolicy | quote }}
          command: ["chown", "-R", "{{ $.Values.securityContext.runAsUser }}:{{ $.Values.securityContext.fsGroup }}", "{{ $.Values.shardsvr.persistence.mountPath }}"]
          securityContext:
            runAsUser: 0
          resources: {{ toYaml $.Values.volumePermissions.resources | nindent 12 }}
          volumeMounts:
            - name: datadir
              mountPath: {{ $.Values.shardsvr.persistence.mountPath }}
        {{- end }}
        {{- with $.Values.shardsvr.dataNode.initContainers }}
        {{- include "mongodb-sharded.tplValue" ( dict "value" . "context" $ ) | nindent 8}}
        {{- end }}
        {{- with $.Values.common.initContainers }}
        {{- include "mongodb-sharded.tplValue" ( dict "value" . "context" $ ) | nindent 8}}
        {{- end }}
      containers:
        - name: mongodb
          image: {{ include "mongodb-sharded.image" $ }}
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          {{- if $.Values.securityContext.enabled }}
          securityContext:
            runAsNonRoot: {{ $.Values.securityContext.runAsNonRoot }}
            runAsUser: {{ $.Values.securityContext.runAsUser }}
          {{- end }}
          ports:
            - containerPort: {{ $.Values.service.port }}
              name: mongodb
          env:
            {{- if $.Values.image.debug }}
            - name: BITNAMI_DEBUG
              value: "true"
            {{- end }}
            - name: MONGODB_SYSTEM_LOG_VERBOSITY
              value: {{ $.Values.common.mongodbSystemLogVerbosity | quote }}
            - name: MONGODB_MAX_TIMEOUT
              value: {{ $.Values.common.mongodbMaxWaitTimeout | quote }}
            - name: MONGODB_DISABLE_SYSTEM_LOG
              {{- if $.Values.mongodbDisableSystemLog }}
              value: "yes"
              {{- else }}
              value: "no"
              {{- end }}
            - name: MONGODB_SHARDING_MODE
              value: "shardsvr"
            - name: MONGODB_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGODB_MONGOS_HOST
              value: {{ include "mongodb-sharded.fullname" $ }}
            - name: MONGODB_INITIAL_PRIMARY_HOST
              value: {{ printf "%s-shard%d-data-0.%s-headless.%s.svc.%s" (include "mongodb-sharded.fullname" $ ) $i (include "mongodb-sharded.fullname" $ ) $.Release.Namespace $.Values.clusterDomain }}
            - name: MONGODB_REPLICA_SET_NAME
              value: {{ printf "%s-shard-%d" ( include "mongodb-sharded.fullname" $ ) $i }}
              {{- if $.Values.common.useHostnames }}
            - name: MONGODB_ADVERTISED_HOSTNAME
              value: "$(MONGODB_POD_NAME).{{ include "mongodb-sharded.fullname" $ }}-headless.{{ $.Release.Namespace }}.svc.{{ $.Values.clusterDomain }}"
              {{- end }}
            {{- if $.Values.usePasswordFile }}
            - name: MONGODB_ROOT_PASSWORD_FILE
              value: "/bitnami/mongodb/secrets/mongodb-root-password"
            - name: MONGODB_REPLICA_SET_KEY_FILE
              value: "/bitnami/mongodb/secrets/mongodb-replica-set-key"
            {{- else }}
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-sharded.secret" $ }}
                  key: mongodb-root-password
            - name: MONGODB_REPLICA_SET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-sharded.secret" $ }}
                  key: mongodb-replica-set-key
            {{- end }}
            - name: MONGODB_ENABLE_IPV6
            {{- if $.Values.common.mongodbEnableIPv6 }}
              value: "yes"
            {{- else }}
              value: "no"
            {{- end }}
            - name: MONGODB_ENABLE_DIRECTORY_PER_DB
            {{- if $.Values.common.mongodbDirectoryPerDB }}
              value: "yes"
            {{- else }}
              value: "no"
            {{- end }}
            {{- if $.Values.shardsvr.dataNode.mongodbExtraFlags }}
            - name: MONGODB_EXTRA_FLAGS
              value: {{ $.Values.shardsvr.dataNode.mongodbExtraFlags | join " " | quote }}
            {{- end }}
          command:
            - /bin/bash
            - /entrypoint/replicaset-entrypoint.sh
          {{- if $.Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - pgrep
                - mongod
            initialDelaySeconds: {{ $.Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.livenessProbe.successThreshold }}
            failureThreshold: {{ $.Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if $.Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: {{ $.Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ $.Values.readinessProbe.successThreshold }}
            failureThreshold: {{ $.Values.readinessProbe.failureThreshold }}
          {{- end }}
          volumeMounts:
            - name: replicaset-entrypoint-configmap
              mountPath: /entrypoint
            - name: datadir
              mountPath: {{ $.Values.shardsvr.persistence.mountPath }}
            {{- if or $.Values.shardsvr.dataNode.config $.Values.shardsvr.dataNode.configCM }}
            - name: config
              mountPath: /bitnami/mongodb/conf/
            {{- end }}
            {{- if $.Values.usePasswordFile }}
            - name: secrets
              mountPath: /bitnami/mongodb/secrets/
            {{- end }}
            {{- if $.Values.common.initScriptsCM }}
            - name: custom-init-scripts-cm
              mountPath: /docker-entrypoint-initdb.d/cm
            {{- end }}
            {{- if $.Values.common.initScriptsSecret }}
            - name: custom-init-scripts-secret
              mountPath: /docker-entrypoint-initdb.d/secret
            {{- end }}
            {{- if $.Values.common.extraVolumeMounts }}
              {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.common.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
            {{- if $.Values.shardsvr.dataNode.extraVolumeMounts }}
              {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.extraVolumeMounts "context" $ ) | nindent 12 }}
            {{- end }}
          resources: {{- toYaml $.Values.shardsvr.dataNode.resources | nindent 12 }}
        {{- if $.Values.metrics.enabled }}
        - name: metrics
          image: {{ include "mongodb-sharded.metrics.image" $ }}
          imagePullPolicy: {{ $.Values.metrics.image.pullPolicy | quote }}
          {{- if $.Values.securityContext.enabled }}
          securityContext:
            runAsNonRoot: {{ $.Values.securityContext.runAsNonRoot }}
            runAsUser: {{ $.Values.securityContext.runAsUser }}
          {{- end }}
          env:
          {{- if $.Values.usePasswordFile }}
            - name: MONGODB_ROOT_PASSWORD_FILE
              value: "/bitnami/mongodb/secrets/mongodb-root-password"
          {{- else }}
            - name: MONGODB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb-sharded.secret" $ }}
                  key: mongodb-root-password
          {{- end }}
          command:
            - sh
            - -ec
            - |-
              #!/bin/sh
              {{- if $.Values.usePasswordFile }}
              export MONGODB_ROOT_PASSWORD="$(cat "${MONGODB_ROOT_PASSWORD_FILE}")"
              {{- end }}
              /bin/mongodb_exporter --mongodb.uri mongodb://root:`echo $MONGODB_ROOT_PASSWORD | sed -r "s/@/%40/g;s/:/%3A/g"`@localhost:{{ $.Values.service.port }}/admin {{ $.Values.metrics.extraArgs }}
          {{- if $.Values.usePasswordFile }}
          volumeMounts:
            - name: secrets
              mountPath: /bitnami/mongodb/secrets/
          {{- end }}
          ports:
            - name: metrics
              containerPort: 9216
          {{- if $.Values.metrics.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ $.Values.metrics.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.metrics.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.metrics.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.metrics.livenessProbe.failureThreshold }}
            successThreshold: {{ $.Values.metrics.livenessProbe.successThreshold }}
          {{- end }}
          {{- if $.Values.metrics.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: {{ $.Values.metrics.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $.Values.metrics.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $.Values.metrics.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $.Values.metrics.readinessProbe.failureThreshold }}
            successThreshold: {{ $.Values.metrics.readinessProbe.successThreshold }}
          {{- end }}
          resources: {{ toYaml $.Values.metrics.resources | nindent 12 }}
        {{- end }}
        {{- with $.Values.shardsvr.dataNode.sidecars }}
        {{- include "mongodb-sharded.tplValue" ( dict "value" . "context" $ ) | nindent 8}}
        {{- end }}
        {{- with $.Values.common.sidecars }}
        {{- include "mongodb-sharded.tplValue" ( dict "value" . "context" $ ) | nindent 8}}
        {{- end }}
      volumes:
        - name: replicaset-entrypoint-configmap
          configMap:
            name: {{ include "mongodb-sharded.fullname" $ }}-replicaset-entrypoint
        {{- if $.Values.usePasswordFile }}
        - name: secrets
          secret:
            secretName: {{ include "mongodb-sharded.secret" $ }}
        {{- end }}
        {{- if $.Values.common.initScriptsCM }}
        - name: custom-init-scripts-cm
          configMap:
            name: {{ include "mongodb-sharded.initScriptsCM" $ }}
            defaultMode: 0755
        {{- end }}
        {{- if $.Values.common.initScriptsSecret }}
        - name: custom-init-scripts-secret
          secret:
            name: {{ include "mongodb-sharded.initScriptsSecret" $ }}
            defaultMode: 0755
        {{- end }}
        {{- if or $.Values.shardsvr.dataNode.config $.Values.shardsvr.dataNode.configCM }}
        - name: config
          configMap:
            name: {{ include "mongodb-sharded.shardsvr.dataNode.configCM" $ }}
        {{- end }}
        {{- if $.Values.common.extraVolumes }}
          {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.common.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if $.Values.shardsvr.dataNode.extraVolumes }}
          {{- include "mongodb-sharded.tplValue" ( dict "value" $.Values.shardsvr.dataNode.extraVolumes "context" $ ) | nindent 8 }}
        {{- end }}
  {{- if $.Values.shardsvr.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: datadir
        annotations:
        {{- range $key, $value := $.Values.shardsvr.persistence.annotations }}
          {{ $key }}: "{{ $value }}"
        {{- end }}
      spec:
        accessModes:
        {{- range $.Values.shardsvr.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ $.Values.shardsvr.persistence.size | quote }}
        {{- include "mongodb-sharded.shardsvr.storageClass" $ | nindent 8}}
  {{- else }}
        - name: datadir
          emptyDir: {}
  {{- end }}
{{- if lt $i (sub $replicas 1) }}
---
{{- end }}
{{- end }}
{{- end }}
