dependencies:
  - name: common
    version: "0.x.x"
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
  - name: mariadb
    version: 7.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: db.bundleTestDB
    tags:
      - phpmyadmin-database
