apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-08T09:37:42Z"
  labels:
    app: exporter-kube-controller-manager
    chart: exporter-kube-controller-manager-0.1.10
    component: kube-controller-manager
    heritage: Helm
    release: kube-prometheus
  name: kube-prometheus-exporter-kube-controller-manager
  namespace: kube-system
  resourceVersion: "5584630"
  selfLink: /api/v1/namespaces/kube-system/services/kube-prometheus-exporter-kube-controller-manager
  uid: 9116fe97-3fb6-4507-b0b8-f86fdd84fcd1
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10252
    protocol: TCP
    targetPort: 10252
  selector:
    component: kube-controller-manager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
