apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2020-05-08T09:37:42Z"
  generation: 2
  labels:
    app: exporter-kube-controller-manager
    chart: exporter-kube-controller-manager-0.1.10
    component: kube-controller-manager
    heritage: Helm
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus-exporter-kube-controller-manager
  namespace: cpaas-system
  resourceVersion: "5584636"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/cpaas-system/servicemonitors/kube-prometheus-exporter-kube-controller-manager
  uid: 3facdd96-fce4-42f3-883e-f22acc223f98
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
    scheme: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: exporter-kube-controller-manager
      component: kube-controller-manager
