apiVersion: v1
kind: Service
metadata:
  labels:
    app: syslog
  name: syslogapi
  namespace: system-ebcpaas
spec:
  ports:
  - name: "10901"
    port: 10901
    targetPort: 10901
  selector:
    app: syslog
