{{- if .Values.configmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "consul.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
  labels: {{- include "consul.labels" . | nindent 4 }}
data:
  config.json: {{- toYaml .Values.configmap | nindent 4}}
  connection.json: |
    {
      "retry_join": ["{{ include "consul.retryjoin.endpoint" . }}"]
    }
{{- end }}
