{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels: {{- include "consul.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
  {{- if .Values.metrics.service.annotations }}
  annotations: {{- toYaml .Values.metrics.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{ if and (eq .Values.metrics.service.type "LoadBalancer") .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http-metrics
      port: 9107
      targetPort: metrics
  selector: {{- include "consul.matchLabels" . | nindent 4 }}
{{- end }}