{{- if .Values.ui.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul.fullname" . }}-ui
  namespace: {{ .Release.Namespace }}
  labels: {{- include "consul.labels" . | nindent 4 }}
  annotations: {{- include "consul.tplValue" ( dict "value" .Values.ui.service.annotations "context" $) | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  {{- if and (eq .Values.ui.service.type "LoadBalancer") (not (empty .Values.ui.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.ui.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.service.uiPort }}
      targetPort: http
      {{- if and (or (eq .Values.ui.service.type "NodePort") (eq .Values.ui.service.type "LoadBalancer")) (not (empty .Values.ui.service.nodePort)) }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}
  selector: {{- include "consul.matchLabels" . | nindent 4 }}
{{- end }}
