apiVersion: v1
data:
  {{- if .Values.mysql.enable }}
  DB_PASSWORD: {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  {{- else if .Values.externalMysql.enable }}
  DB_PASSWORD: {{ .Values.externalMysql.password | b64enc | quote }}
  {{- else }}
  DB_PASSWORD: {{ required "至少填写一种数据库信息" .Values.mysql.enable }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "paas.fullname" . }}
type: Opaque
