apiVersion: v1
kind: Service
metadata:
  name: {{ include "paas.fullname" . }}
  labels:
{{ include "paas.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http1
    - port: 8002
      targetPort: 8002
      protocol: TCP
      name: http2
    - port: 8003
      targetPort: 8003
      protocol: TCP
      name: http3
  selector:
    app.kubernetes.io/name: {{ include "paas.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
