apiVersion: v1
kind: Service
metadata:
  labels:
    app: coreservice
    release: {{ .Release.Name }}
  name: coreservice
spec:
  ports:
    - name: "http"
      port: 60007
      targetPort: 60007
  selector:
    app: coreservice
    release: {{ .Release.Name }}
