apiVersion: v1
kind: Service
metadata:
  labels:
    app: apiserver
    release: {{ .Release.Name }}
  name: apiserver
spec:
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
  selector:
    app: apiserver
    release: {{ .Release.Name }}
