apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
    release: {{ .Release.Name }}
  name: webserver
spec:
  ports:
    - name: "http"
      port: 8090
      targetPort: 8090
  selector:
    app: webserver
    release: {{ .Release.Name }}
