apiVersion: v1
kind: Service
metadata:
  labels:
    app: adminserver
    release: {{ .Release.Name }}
  name: adminserver
spec:
  ports:
    - name: "http"
      port: 60004
      targetPort: 60004
  selector:
    app: adminserver
    release: {{ .Release.Name }}
