apiVersion: v1
kind: Service
metadata:
  labels:
    app: datacollection
    release: {{ .Release.Name }}
  name: datacollection
spec:
  ports:
    - name: "http"
      port: 60005
      targetPort: 60005
  selector:
    app: datacollection
    release: {{ .Release.Name }}
