apiVersion: v1
kind: Service
metadata:
  labels:
    app: synchronizeserver
    release: {{ .Release.Name }}
  name: synchronizeserver
spec:
  ports:
    - name: "http"
      port: 60010
      targetPort: 60010
  selector:
    app: synchronizeserver
    release: {{ .Release.Name }}
