apiVersion: v1
kind: Service
metadata:
  labels:
    app: eventserver
    release: {{ .Release.Name }}
  name: eventserver
spec:
  ports:
    - name: "http"
      port: 60009
      targetPort: 60009
  selector:
    app: eventserver
    release: {{ .Release.Name }}
