apiVersion: v1
kind: Service
metadata:
  labels:
    app: taskserver
    release: {{ .Release.Name }}
  name: taskserver
spec:
  ports:
    - name: "http"
      port: 60012
      targetPort: 60012
  selector:
    app: taskserver
    release: {{ .Release.Name }}
