apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostserver
    release: {{ .Release.Name }}
  name: hostserver
spec:
  ports:
    - name: "http"
      port: 60001
      targetPort: 60001
  selector:
    app: hostserver
    release: {{ .Release.Name }}
