apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: webserver
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-configures
spec:
  rules:
  - host: {{ .Values.cmdb.webserverURL }}
    http:
      paths:
      - backend:
          serviceName: webserver
          servicePort: 8090
        path: /
        pathType: ImplementationSpecific
 
