apiVersion: v1
kind: Service
metadata:
  labels:
    app: toposerver
    release: {{ .Release.Name }}
  name: toposerver
spec:
  ports:
    - name: "http"
      port: 60002
      targetPort: 60002
  selector:
    app: toposerver
    release: {{ .Release.Name }}
