apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    release: {{ .Release.Name }}
  name: elasticsearch
spec:
  ports:
    - name: "http"
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
    release: {{ .Release.Name }}
