apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
    release: {{ .Release.Name }}
  name: redis
spec:
  ports:
    - name: "http"
      port: 6379
      targetPort: 6379
  selector:
    app: redis
    release: {{ .Release.Name }}
