apiVersion: v1
kind: Namespace
metadata:
  name: jupyterlab
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  name: jupyter
  namespace: jupyterlab
spec:
  rules:
    - host: jupyter.ebcpaas.com
      http:
        paths:
          - backend:
              serviceName: jupyter
              servicePort: 8888
            path: /
  tls:
    - secretName: ingress-tls
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jupyter
  name: jupyter
  namespace: jupyterlab
spec:
  ports:
    - name: "8888"
      port: 8888
      targetPort: 8888
  selector:
    app: jupyter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jupyter
  name: jupyter
  namespace: jupyterlab
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: jupyter
          image: jupyterlab:1.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PY_INDEX
              value: https://nexus.ebcpaas.com/repository/pypi-public/simple/
            - name: PY_TRUST
              value: nexus.ebcpaas.com
            - name: NPM_REGISTRY
              value: https://nexus.ebcpaas.com/repository/npm-public/
            - name: DEB_SOURCE
              value: https://nexus.ebcpaas.com/repository/apt-deb/
          #- name: JUPYTER_ADDR
          #  value: 0.0.0.0
          #- name: JUPYTER_PORT
          #  value: 8888
          #- name: JUPYTER_DIR
          #  value: /workspace
          #- name: JUPYTER_TOKEN
          #  value: jupyter
          #- name: JUPYTER_MODE
          #  value: core
          resources: {}
          tty: true
          ports:
            - containerPort: 8888
          volumeMounts:
            - mountPath: /workspace
              name: nfsshare
              subPath: jupyter
      #imagePullSecrets:
      #- name: ebpaas-registry-20.20
      restartPolicy: Always
      volumes:
        - name: nfsshare
          nfs:
            path: /var/nfsshare
            server: 25.2.24.21
