{{- if and .Values.secrets.bitnamiSealedSecrets.enabled .Values.secrets.bitnamiSealedSecrets.sealedSecretFiles }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  {{- if .Values.secrets.bitnamiSealedSecrets.sealedSecretFilesAnnotations }}
  annotations:
    {{- range $key, $val := .Values.secrets.bitnamiSealedSecrets.sealedSecretFilesAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
  name: {{ .Release.Name }}-secretfiles
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  encryptedData:
    {{- range $key, $val := .Values.secrets.bitnamiSealedSecrets.sealedSecretFiles }}
    {{ $key }}: {{ $val }}
    {{- end }}
{{- end }}