apiVersion: v1
appVersion: 7.1.5
description: The leading tool for querying and visualizing time series and metrics.
home: https://grafana.net
icon: file://../logo.png
kubeVersion: ^1.8.0-0
maintainers:
- email: zanhsieh@gmail.com
  name: zanhsieh
- email: rluckie@cisco.com
  name: rtluckie
- email: maor.friedman@redhat.com
  name: maorfr
name: grafana
sources:
- https://github.com/grafana/grafana
version: 5.6.2
