apiVersion: v1
appVersion: 13.3.5
description: Web-based Git-repository manager with wiki and issue-tracking features.
home: https://about.gitlab.com/
icon: file://../logo.png
keywords:
- gitlab
maintainers:
- email: support@gitlab.com
  name: GitLab Inc.
name: gitlab
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
version: 4.3.5
