apiVersion: v1
appVersion: v1.0.1
description: A Helm chart for cert-manager
home: https://github.com/jetstack/cert-manager
icon: file://../logo.svg
keywords:
- cert-manager
- kube-lego
- letsencrypt
- tls
maintainers:
- email: james@jetstack.io
  name: munnerz
name: cert-manager
sources:
- https://github.com/jetstack/cert-manager
version: v1.0.1
