apiVersion: v1
kind: Secret
metadata:
  name: {{ template "artifactory-ha.fullname" . }}
  labels:
    app: {{ template "artifactory-ha.name" . }}
    chart: {{ template "artifactory-ha.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if not (or .Values.artifactory.masterKey .Values.global.masterKey) }}
  {{- if not (or .Values.artifactory.masterKeySecretName .Values.global.masterKeySecretName) }}
    {{ required  ".Values.artifactory.masterKey or .Values.artifactory.masterKeySecretName is required! This enables a node to connect to a HA cluster" .Values.artifactory.masterKey }}
  {{- end }}
  {{- end }}
  {{- if or .Values.artifactory.masterKey .Values.global.masterKey }}
  {{- if not (or .Values.artifactory.masterKeySecretName .Values.global.masterKeySecretName) }}
  master-key: {{ include "artifactory-ha.masterKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if or .Values.artifactory.joinKey .Values.global.joinKey }}
  {{- if not (or .Values.artifactory.joinKeySecretName .Values.global.joinKeySecretName) }}
  join-key: {{ include "artifactory-ha.joinKey" . | b64enc | quote }}
  {{- end }}
  {{- end }}
