{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "prometheus-operator.operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "prometheus-operator.operator.labels" . | nindent 4 }}
{{- include "prometheus-operator.operator.imagePullSecrets" . }}
{{- end }}
