apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: event-exporter
  name: event-exporter
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: event-exporter
  name: event-exporter
  namespace: cpaas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    name: event-exporter
  name: event-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: event-exporter
  namespace: cpaas-system
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: event-exporter
  name: event-exporter
  namespace: cpaas-system
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9102
  selector:
    app: event-exporter
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: event-exporter
  name: event-exporter
  namespace: cpaas-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-exporter
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-exporter
    spec:
      containers:
      - command:
        - ./event_exporter
        image: regdev.ebchina.com/library/event-exporter:v0.3.0
        imagePullPolicy: Always
        name: event-exporter
        ports:
        - containerPort: 9102
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 100Mi
          requests:
            memory: 40Mi
      securityContext: {}
      serviceAccount: event-exporter
      serviceAccountName: event-exporter
 
