{{- if .Values.mongos.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-sharded.fullname" . }}-mongos
  labels: {{- include "mongodb-sharded.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongos
data:
  mongodb.conf: |-
    {{- include "mongodb-sharded.tplValue" (dict "value" .Values.mongos.config "context" $) | indent 4 }}
{{- end }}