{{- if .Values.mongos.pdb.enabled -}}
kind: PodDisruptionBudget
apiVersion: policy/v1beta1
metadata:
  name: {{ include "mongodb-sharded.fullname" . }}-mongos
  labels: {{- include "mongodb-sharded.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongos
spec:
  selector:
    matchLabels: {{- include "mongodb-sharded.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongos
  {{- if .Values.mongos.pdb.minAvailable }}
  minAvailable: {{ .Values.mongos.pdb.minAvailable | int }}
  {{- end }}
  {{- if .Values.mongos.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.mongos.pdb.maxUnavailable | int }}
  {{- end }}
{{- end -}}
