apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-08T09:37:42Z"
  labels:
    alertmanager: kube-prometheus
    app: alertmanager
    chart: alertmanager-0.1.5
    heritage: Helm
    release: kube-prometheus
  name: kube-prometheus-alertmanager
  namespace: cpaas-system
  resourceVersion: "4546"
  selfLink: /api/v1/namespaces/cpaas-system/services/kube-prometheus-alertmanager
  uid: edaa724e-71ef-479e-b17d-2f6b2b0a7be6
spec:
  clusterIP: 10.199.163.174
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    alertmanager: kube-prometheus
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
