apiVersion: v1
appVersion: 0.9.4
description: CoreOS etcd-operator Helm chart for Kubernetes
home: https://github.com/coreos/etcd-operator
icon: file://../logo.png
maintainers:
- email: lachlan@deis.com
  name: lachie83
- email: jaescobar.cell@gmail.com
  name: alejandroEsc
name: etcd-operator
sources:
- https://github.com/coreos/etcd-operator
version: 0.11.0
