apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2020-08-09T13:21:01Z"
  creationTimestamp: "2020-05-08T09:37:42Z"
  labels:
    app: prometheus
    chart: prometheus-0.0.50
    heritage: Helm
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus
  namespace: cpaas-system
  resourceVersion: "121540433"
  selfLink: /api/v1/namespaces/cpaas-system/endpoints/kube-prometheus
  uid: 6d482bfc-1786-4893-a15c-d0bf953083e9
subsets:
- addresses:
  - ip: 10.199.12.26
    nodeName: 25.2.20.53
    targetRef:
      kind: Pod
      name: prometheus-kube-prometheus-0
      namespace: cpaas-system
      resourceVersion: "121540431"
      uid: 4ebd21fe-bcc0-405e-a934-3f962cb14a07
  ports:
  - name: http
    port: 9090
    protocol: TCP
