annotations:
  category: Database
apiVersion: v1
appVersion: 10.5.5
description: MariaDB Galera is a multi-master database cluster solution for synchronous
  replication and high availability.
engine: gotpl
home: https://mariadb.org
icon: file://../logo.png
keywords:
- mariadb
- mysql
- database
- sql
- prometheus
- galera
- percona
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: mariadb-galera
sources:
- https://github.com/bitnami/bitnami-docker-mariadb-galera
- https://github.com/prometheus/mysqld_exporter
version: 4.3.3
