apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  creationTimestamp: "2020-05-08T09:37:42Z"
  generation: 1
  labels:
    app: exporter-kube-proxy
    chart: exporter-kube-proxy-0.1.0
    component: kube-proxy
    heritage: Helm
    prometheus: kube-prometheus
    release: kube-prometheus
  name: kube-prometheus-exporter-kube-proxy
  namespace: cpaas-system
  resourceVersion: "4634"
  selfLink: /apis/monitoring.coreos.com/v1/namespaces/cpaas-system/servicemonitors/kube-prometheus-exporter-kube-proxy
  uid: 824af1fe-0121-46d2-aec4-bacb36f94c1a
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    interval: 15s
    port: http-metrics
    scheme: http
    tlsConfig:
      caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      insecureSkipVerify: true
  jobLabel: component
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: exporter-kube-proxy
      component: kube-proxy
