annotations:
  category: Infrastructure
apiVersion: v1
appVersion: 0.35.0
description: Chart for the nginx Ingress controller
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller
icon: file://../logo.png
keywords:
- ingress
- nginx
- http
- web
- www
- reverse proxy
maintainers:
- email: containers@bitnami.com
  name: Bitnami
name: nginx-ingress-controller
sources:
- https://github.com/bitnami/bitnami-docker-nginx-ingress-controller
- https://github.com/kubernetes/ingress-nginx
version: 5.5.1
