#Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentsdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opentsdb.name" . }}
    {{- include "opentsdb.labels" . | nindent 4 }}
spec:
  ports:
  - name: opentsdb
    port: 4242
    protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "opentsdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
