apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentsdb.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "opentsdb.name" . }}
    {{- include "opentsdb.labels" . | nindent 4 }}
data:
  create_hbase_tables.sh: |-
{{ tpl (.Files.Get "resources/config/create_hbase_tables.sh") . | indent 4 }}
  hbase_script.txt: |-
{{ .Values.init_hbase_script | indent 4 }}
