apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentsdb.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "opentsdb.name" . }}
    {{- include "opentsdb.labels" . | nindent 4 }}
data:
  opentsdb.conf: |-
{{ tpl (.Files.Get "resources/config/opentsdb.conf") . | indent 4 }}
  logback.xml: |
{{ tpl (.Files.Get "resources/config/logback.xml") . | indent 4 }}
