{{- if and .Values.controllerManager.enabled .Values.controllerManager.service.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-controller-manager
  labels:
    app: {{ $fullName }}-controller-manager
    {{- with .Values.controllerManager.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.controllerManager.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controllerManager.service.type }}
  {{- with .Values.controllerManager.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  ports:
  - port: {{ .Values.controllerManager.service.port }}
    name: client
    {{- with .Values.controllerManager.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    app: {{ $fullName }}-controller-manager
{{- end }}
