{{- if or .Values.admin.enabled .Values.admin.job.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-kubeadm-config
data:
  kubeadmcfg.yaml: |+
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    {{- with .Values.controlPlaneEndpoint }}
    controlPlaneEndpoint: {{ . }}
    {{- end }}
{{- end }}
