{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-ca"
spec:
  commonName: "{{ $fullName }}-pki-ca"
  secretName: "{{ $fullName }}-pki-ca"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  organization:
  - "{{ $fullName }}"
  usages:
  - "signing"
  - "digital signature"
  - "key encipherment"
  - "cert sign"
  isCA: true
  issuerRef:
    name: "{{ $fullName }}-selfsigning-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: "{{ $fullName }}-issuer"
spec:
  ca:
    secretName: "{{ $fullName }}-pki-ca"
---
{{- $svcName1 := printf "%s-apiserver" $fullName }}
{{- $svcName2 := printf "%s-apiserver.%s" $fullName .Release.Namespace }}
{{- $svcName3 := printf "%s-apiserver.%s.svc" $fullName .Release.Namespace }}
{{- $podName1 := printf "*.%s-apiserver" $fullName }}
{{- $podName2 := printf "*.%s-apiserver.%s" $fullName .Release.Namespace }}
{{- $podName3 := printf "*.%s-apiserver.%s.svc" $fullName .Release.Namespace }}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-apiserver"
spec:
  commonName: "{{ $fullName }}-pki-apiserver"
  secretName: "{{ $fullName }}-pki-apiserver"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  organization:
  - "{{ $fullName }}"
  usages:
  - "signing"
  - "key encipherment"
  - "server auth"
  dnsNames:
  - "{{ $svcName1 }}"
  - "{{ $svcName2 }}"
  - "{{ $svcName3 }}"
  - "{{ $podName1 }}"
  - "{{ $podName2 }}"
  - "{{ $podName3 }}"
  - "localhost"
  {{- with .Values.apiServer.certSANs.dnsNames }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  ipAddresses:
  - "127.0.0.1"
  - "10.96.0.1"
  {{- with .Values.apiServer.service.loadBalancerIP }}
  {{- if not (has . $.Values.apiServer.certSANs.ipAddresses) }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
  {{- with .Values.apiServer.certSANs.ipAddresses }}
  {{- . | toYaml | nindent 2 }}
  {{- end }}
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-apiserver-kubelet-client"
spec:
  commonName: "{{ $fullName }}-pki-apiserver-kubelet-client"
  secretName: "{{ $fullName }}-pki-apiserver-kubelet-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  organization:
  - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-issuer"
    kind: Issuer
