{{- if .Values.admin.job.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-kubeadm-scripts
data:
  configure-cluster.sh: |+
    {{- tpl (.Files.Get "scripts/configure-cluster.sh") . | nindent 4 }}
{{- end }}
