apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-05-08T09:37:42Z"
  labels:
    app: exporter-node
    chart: exporter-node-0.4.5
    component: node-exporter
    heritage: Helm
    release: kube-prometheus
  name: kube-prometheus-exporter-node
  namespace: cpaas-system
  resourceVersion: "4563"
  selfLink: /api/v1/namespaces/cpaas-system/services/kube-prometheus-exporter-node
  uid: 79e3d1e4-ff74-4ef7-8cd7-8d2a74263dac
spec:
  clusterIP: 10.199.165.42
  ports:
  - name: metrics
    port: 9100
    protocol: TCP
    targetPort: metrics
  selector:
    app: kube-prometheus-exporter-node
    component: node-exporter
    release: kube-prometheus
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
