{{- if and (not .Values.configsvr.external.host) .Values.configsvr.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-sharded.fullname" . }}-configsvr
  labels: {{- include "mongodb-sharded.labels" . | nindent 4 }}
    app.kubernetes.io/component: configsvr
data:
  mongodb.conf: |-
    {{- include "mongodb-sharded.tplValue" (dict "value" .Values.configsvr.config "context" $) | indent 4 }}
{{- end }}