NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.ebtech.tebchain-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.ebtech.tebchain-cert.pem
    OrganizationalUnitIdentifier: peer
