apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus.fullname" . }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "nexus.labels" . | nindent 4 }}
    {{- if .Values.nexus.extraLabels }}
      {{- with .Values.nexus.extraLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      protocol: TCP
      name: nexus-ui
    - port: 5000
      protocol: TCP
      name: docker-default
  selector:
    {{- include "nexus.selectorLabels" . | nindent 4 }}
    {{- if .Values.nexus.extraSelectorLabels }}
      {{- with .Values.nexus.extraSelectorLabels }}
        {{ toYaml . | indent 4 }}
      {{- end }}
    {{- end }}     
